import {
  Calendar,
  CalendarPlus,
  MapPin,
  Repeat,
  Rss,
  ChevronLeft,
  Maximize,
  Printer,
  ZoomIn,
  ZoomOut,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  AtSign,
  Bell,
  BellOff,
  Bold,
  Bookmark,
  Check,
  CircleAlert,
  CheckCheck,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  Clock,
  Code,
  Copy,
  Download,
  GripVertical,
  ExternalLink,
  Eye,
  File,
  FileArchive,
  FileSpreadsheet,
  FileText,
  Fingerprint,
  Folder,
  FolderOpen,
  FolderPlus,
  Globe,
  HardDrive,
  Hash,
  House,
  Heading1,
  Heading2,
  Heading3,
  Heart,
  Image as ImageIcon,
  Import,
  Inbox,
  Info,
  Italic,
  Languages,
  Keyboard,
  KeyRound,
  LayoutGrid,
  LifeBuoy,
  List,
  ListChecks,
  ListOrdered,
  Lock,
  LogOut,
  type LucideIcon,
  Mail,
  MessageSquare,
  Monitor,
  Moon,
  Minus,
  MoreHorizontal,
  Paperclip,
  PartyPopper,
  Pin,
  Play,
  Plus,
  Quote,
  RefreshCw,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Smile,
  Sun,
  SmilePlus,
  Table,
  SquareCode,
  SquarePen,
  Star,
  StarOff,
  ThumbsUp,
  Trash2,
  TriangleAlert,
  Type,
  Undo2,
  Upload,
  UserMinus,
  UserPlus,
  Users,
  X,
} from "lucide-react";
import type { CSSProperties } from "react";

/**
 * Icon set used across the app, keyed by the kebab-case Lucide names the design-system
 * mockups reference. Sovereignty rule: icons are the `lucide-react` package (ISC,
 * community-governed), rendered as inline SVG. No runtime CDN, CSP-safe. Extend this map
 * when a screen needs a new glyph rather than reaching for a network URL.
 */
const ICONS: Record<string, LucideIcon> = {
  archive: Archive,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-down": ArrowUpDown,
  "at-sign": AtSign,
  bell: Bell,
  "bell-off": BellOff,
  bold: Bold,
  bookmark: Bookmark,
  calendar: Calendar,
  "calendar-plus": CalendarPlus,
  check: Check,
  "check-check": CheckCheck,
  "circle-alert": CircleAlert,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  maximize: Maximize,
  printer: Printer,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
  clock: Clock,
  code: Code,
  copy: Copy,
  download: Download,
  "grip-vertical": GripVertical,
  "external-link": ExternalLink,
  eye: Eye,
  file: File,
  "file-archive": FileArchive,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  fingerprint: Fingerprint,
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  globe: Globe,
  "hard-drive": HardDrive,
  hash: Hash,
  house: House,
  "heading-1": Heading1,
  "heading-2": Heading2,
  "heading-3": Heading3,
  heart: Heart,
  image: ImageIcon,
  import: Import,
  inbox: Inbox,
  info: Info,
  italic: Italic,
  languages: Languages,
  keyboard: Keyboard,
  "key-round": KeyRound,
  "layout-grid": LayoutGrid,
  "life-buoy": LifeBuoy,
  list: List,
  "list-checks": ListChecks,
  "list-ordered": ListOrdered,
  lock: Lock,
  "log-out": LogOut,
  mail: Mail,
  "map-pin": MapPin,
  "message-square": MessageSquare,
  monitor: Monitor,
  moon: Moon,
  minus: Minus,
  "more-horizontal": MoreHorizontal,
  paperclip: Paperclip,
  "party-popper": PartyPopper,
  pin: Pin,
  play: Play,
  plus: Plus,
  quote: Quote,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  rss: Rss,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  shield: Shield,
  "shield-check": ShieldCheck,
  smile: Smile,
  "smile-plus": SmilePlus,
  sun: Sun,
  table: Table,
  "square-code": SquareCode,
  "square-pen": SquarePen,
  star: Star,
  "star-off": StarOff,
  "thumbs-up": ThumbsUp,
  "trash-2": Trash2,
  // A warning that is not an error: something to read before acting, not a refusal.
  "alert-triangle": TriangleAlert,
  type: Type,
  upload: Upload,
  "user-minus": UserMinus,
  "undo-2": Undo2,
  "user-plus": UserPlus,
  users: Users,
  x: X,
};

/**
 * A registered icon name.
 *
 * `IconProps.name` is typed from it rather than left as `string`, because an unregistered name
 * rendered nothing at all: a `console.warn` in development is no help to whoever did not have the
 * dev server open, and a missing icon reached a deployed instance that way. It is a build error now,
 * next to the typo.
 */
export type IconName = keyof typeof ICONS;

export type IconProps = {
  name: IconName;
  size?: number;
  title?: string;
  className?: string;
  style?: CSSProperties;
};

/** Lucide glyph, coloured by currentColor. `title` makes it an accessible image. */
export function Icon({ name, size = 16, title, className, style }: IconProps) {
  const Glyph = ICONS[name];
  if (!Glyph) {
    if (process.env.NODE_ENV !== "production") {
      console.warn(`Icon "${name}" is not registered in components/ds/Icon.tsx`);
    }
    return null;
  }
  return (
    <Glyph
      size={size}
      className={className}
      style={style}
      role={title ? "img" : "presentation"}
      aria-label={title}
      aria-hidden={title ? undefined : true}
    />
  );
}
